title: Assertive Script
description: Documentation for Assertive Script
theme: just-the-docs

url: https://assertivescript.com
aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# For copy button on code
enable_copy_code_button: true

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.9.1"

callouts:
  warning:
    title: Warning
    color: red
