title: Assertive Script
description: Documentation for the Assertive scripting language
theme: just-the-docs

url: https://assertivescript.com
aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# For copy button on code
enable_copy_code_button: true
